//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Progress
    {
        public int UserID { get; set; }
        public int CourseID { get; set; }
        public string UserName { get; set; }
        public int Prog_status { get; set; }
        public Nullable<double> Test_scores { get; set; }
        public string Certi_status { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
